name: sentinal
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.0.0
  go_router: ^14.6.3
  lottie: ^3.2.0
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  awesome_dialog: ^3.2.1
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  cloud_functions: ^5.3.0
  equatable: ^2.0.7
  animated_bottom_navigation_bar: ^1.3.3
  theme_provider: ^0.6.0
  local_auth: ^2.3.0
  flutter_svg: ^2.0.17
  flutter_slidable: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
    - assets/svg/
  fonts:
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf


